config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root "recipes#index"
  resources :recipes
  resources :things
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '選択してください' },
    { id: 2, name: '主菜' },
    { id: 3, name: '副菜' },
    { id: 4, name: 'ご飯' },
    { id: 5, name: '汁物' },
    { id: 6, name: 'その他' },
  ]
end

app/models/ckeditor/asset.rb
# frozen_string_literal: true

class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
# frozen_string_literal: true

class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
# frozen_string_literal: true

class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/cook.rb
class Cook < ApplicationRecord
  belongs_to :recipe
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to   :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category

  #belongs_to   :user
  has_many     :materials, dependent: :destroy
  has_one      :cook, dependent: :destroy
  has_one_attached :image

  accepts_nested_attributes_for :materials, allow_destroy: true
  accepts_nested_attributes_for :cook, allow_destroy: true
end

app/models/thing.rb
class Thing < ActiveHash::Base
  self.data = [
    # 個
    { id: 1, name: 'じゃがいも',spoon:"", unit: "個"},
    { id: 2, name: '玉ねぎ', spoon:"",unit: "個"},
    { id: 3, name: 'なすび', spoon:"",unit: "個" },
    { id: 4, name: 'ピーマン', spoon:"",unit: "個" },
    { id: 5, name: 'しいたけ', spoon:"",unit: "個" },
    { id: 6, name: 'お好みのルー', spoon:"",unit: "個" },

    # 本
    { id: 101, name: 'にんじん', unit: "本" },
    { id: 102, name: 'ねぎ', unit: "本" },
    { id: 103, name: '大根', unit: "本" },

    # 束
    { id: 201, name: 'ほうれん草' , unit: "束"},
    { id: 202, name: 'ニラ', unit: "束" },

    # ml
    { id: 301, name: '水', spoon:"", unit: "ml" },
    { id: 302, name: '醤油' , spoon:"大さじ", unit: "" },
    { id: 303, name: 'みりん', spoon:"大さじ", unit: "" },
    { id: 304, name: '酒', spoon:"大さじ", unit: "" },
    { id: 305, name: 'ごま油', spoon:"大さじ", unit: "" },

    # 袋
    { id: 401, name: 'もやし' },
    { id: 402, name: 'しらたき' },

    # g
    { id: 501, name: '砂糖' },
    { id: 502, name: '豚肉(細切れ)' },
    { id: 503, name: '鶏(胸肉)' },
    { id: 504, name: '鶏(もも肉)' },
  ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all.order("created_at DESC")
  end


  def new
    @recipe = Recipe.new
    @material = @recipe.materials.build
    # undefined methodbuild' for nil:NilClass`
    # has_oneで繋がってるときは[インスタンス名.build_アソシエーション名]
    @cook = @recipe.build_cook
  end


  def create
    @recipe = Recipe.new(recipe_params)
    binding.pry
    if @recipe.save
      redirect_to root_path
      # format.html { redirect_to @recipe, notice: 'Post was successfully created.' }
      # format.json { render :index, status: :created, location: @recipe }
    else
      render :new
      # format.html { render :new }
      # format.json { render json: @recipe.errors, status: :unprocessable_entity }
    end
  end

  def show
    @recipe.find(params[:id])
  end



  private

  def recipe_params
    params.require(:recipe).permit(:image, :title ,:feature,:category_id, :date, :cook_time, 
      materials_attributes:[:id, :recipe_id, :thing_id, :amount, :_destroy],
      cook_attributes:[:id, :recipe_id ,:body, :_destroy])
  end
end
  # def get_unit
  #   @unit = Unit.all.to_json
  # end 

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Editor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.ckeditor.com/4.15.0/standard/ckeditor.js"></script>
    <%= javascript_include_tag Ckeditor.cdn_url%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_material_fields.html.erb
<div class="nested-fields" id="nested">

  <% thing_options = Thing.order(:id).map { |c| [c.name, c.id, data: { unit: c.unit, spoon:c.spoon }] } %>
  <span><%= f.select(:thing_id, thing_options, { prompt: "---"}, {class:"select", data:{select:0}, id:"thing-select" })%></span> <%#= " %>
  <%#= f.collection_select(:thing_id, Thing.all, :id, :name, {}, {class:"select-box", id:"thing-select", data: {index:0} }) %>

  <span class="box-spoon" id='spoon-auto' data-spoon='0'>単位</span>
  <%= f.text_field :amount, placeholder:"(例)1.5", class:"amount-box" %>
  <span class="box-unit" id='unit-auto' data-unit='0'>単位</span>
  <%= link_to_remove_association "材料を削除", f %>
</div>

app/views/recipes/index.html.erb
<h1>Recipes#index</h1>

<div class='btn'>
  <%= link_to '新規作成', new_recipe_path, method: :get, class: "new-recipe" %>
</div>

<ul class='recipe-lists'>
  <% @recipes.each do |recipe|%>
    <li class='list'>
      <%#= link_to item_path(item.id) do %>
        <div class='recipe-img-content'>
          <%= image_tag recipe.image, class: "recipe-img" %> 
        </div>
        <div class='recipe-info'>
          <h3 class='recipe-name'>
            <%= recipe.title %>
          </h3>
        </div>  
        <div class='recipe-time'>
          <%= recipe.category.name %>
        </div>
      <%# end %>
    </li>
  <% end %>
        

app/views/recipes/new.html.erb
<h1>Recipes#new</h1>

<%# 親のフォーム %>
<%= form_with(model: @recipe, local: true) do |f| %>
  <div class="click-upload">
    <p>
      クリックしてファイルをアップロード
    </p>
    <%= f.file_field :image, id:"item-image" %>
  </div>

  <%= f.label "料理名"%>
  <%= f.text_field :title %>

  <%= f.label "ポイント！"%>
  <%= f.text_field :feature %>

  <%= f.label "カテゴリー"%>
  <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"categoey-select"}) %>

  <%= f.label "日持ち"%>
  <%= f.text_field :date %>

  <%= f.label "調理時間の目安"%>
  <%= f.text_field :cook_time %>
  <!-- プルダウンに変える -->

  <%= f.label "材料" %>

  <div id="btn-event" class="onegai">
    <div class="links">
      <%= link_to_add_association "材料を追加", f, :materials,
      class: 'btn btn-success',
      id: 'add-btn',
      data: {
        #association_insertion_traversal: 'closest',
        association_insertion_node: '#detail-association-insertion-point',
        association_insertion_method: 'after'}
        # data-association-insertion-node： '#追加分の差し込み先'
        # data-association-insertion-method：'差し込み先に対して上なのか下なのか...'
        #'before'差し込み先の上 'after'差し込み先の下 'append'追加されたものの下 'prepend'追加されたものの上
      %>
    </div>

    <%# ここに挿入さきがないと上にコンテンツが挿入されないため、Id付与できない  %>
    <div id="detail-association-insertion-point"></div>

    <%# 子供の追加要素へ飛ばす %>
    <div class="materials" id="categories">
    <%= f.fields_for :materials do |form| %>
      <%= render "material_fields", f: form %>
      <!-- f: formとなっていなかったためformが渡せていなかった-->
    <% end %>
    </div>
  </div>

<%# CKエディター %>
  <div class="cook">
    <%= f.fields_for :cook do |form| %>
      <div><%= form.cktext_area :body, class: "ck-editer" %></div>
    <% end %>
  </div>

<%# フォームの送信ボタン %>
  <div class="actions">
    <%= f.submit "送信" %>
  </div>
<% end %>

app/views/recipes/show.html.erb
<h1>Recipes#show</h1>